# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2da4d53eaa0404c7df1273c723aed077"
name = "Test-Soumesh"
handle = "test-soumesh"
application_url = "https://jill-ide-baking-psychiatry.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://jill-ide-baking-psychiatry.trycloudflare.com/auth/callback",
  "https://jill-ide-baking-psychiatry.trycloudflare.com/auth/shopify/callback",
  "https://jill-ide-baking-psychiatry.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
